export const FETCH_USER_DETAILS = 'FETCH_USER_DETAILS';
export const FETCH_USER_REPOSITORIES = 'FETCH_USER_REPOSITORIES';
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
